TARGET=pongix.exe

OBJS = cursor.o dirty.o fuente.o marcador.o creditos.o juego.o \
	  menu.o mundo.o paleta.o pelota.o pongix.o util.o control.o

LDFLAGS = -lm -lSDL_net -lSDL_image -lSDL

all: $(TARGET)

$(TARGET): $(OBJS)

.PHONY: clean
clean:
	rm -f $(OBJS) $(TARGET) *.exe *.ELF *.elf *.s *.o
